#!/bin/bash

root=/Users/oz/Documents/Obsidian/ozpoo.github.io
out="$root"/site

pr_site_head() {
  echo '<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" loading-fonts>
<head>
  <meta charset="utf-8" />
  <meta name="generator" content="ozdoc 0.0.0" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes" />
  <title>index</title>
  <link rel="stylesheet" href="reset.css">
  <link rel="stylesheet" href="typography.css">
  <link rel="stylesheet" href="font/style.css">
  <link rel="stylesheet" href="style.css">
</head>'
}

pr_site_header() {
  echo '<header>
  <strong>Made width code.</strong>
  <nav>
      <a href="index.html">Index</a>
      <a href="a-way-in-index.html">A Way In</a>
      <a href="field-notes-index.html">Field Notes</a>
      <a href="working-inquiries-index.html">Working Inquiries</a>
      <a href="practices-index.html">Practices</a>
      <a href="frameworks-index.html">Frameworks</a>
  </nav>
</header>
<hr>'
}

pr_site_footer() {
  echo '<hr>
<footer>
  <p><em>Still figuring it out.</em></p>
</footer>
<script src="script.js"></script>'
}

pr() {
  case "$1" in
    site-head) pr_site_head ;;
    site-header) pr_site_header ;;
    site-footer) pr_site_footer ;;
  esac
}

render() {
  echo $(pandoc -f markdown-auto_identifiers+mark+hard_line_breaks -t html "$1")
}

build_style() {
  cp -f "$root/reset.css" "$out"
  cp -f "$root/typography.css" "$out"
  cp -f "$root/style.css" "$out"
   cp -f "$root/script.js" "$out"
  # cp -f "$root/font.css" "$out"
  # cp -rf "$root/font" "$out"
}

build_index() {
  local dirs="$1"
  echo "Processing index.md..."
  while IFS= read -r line; do
    if [[ "$line" =~ ^include::(.*\.md)$ ]]; then
      file="${BASH_REMATCH[1]}"
      txt=$(cat "$file")
      echo "---"
      echo
      echo "##$txt"
      echo
    else
      echo "$line"
    fi
  done < "index.md" > "temp.md"
  cat << EOF > "$out"/index.html
$(pr site-head)
<body>
$(pr site-header | sed 's/^/\t/')
  <main>
$(render temp.md | sed 's/^/\t\t/')
  </main>
$(pr site-footer | sed 's/^/\t/')
</body>
EOF
  cat << EOF > "$out"/content/index.html
$(render temp.md)
EOF
rm "temp.md"
}

build_file() {
  local file="$1" src="$2"
  echo "Processing $file..."
  name="${file#"$src/"}"
  name=$(echo "${name//\'/}")
  name=$(echo "${name// /-}" | tr '[:upper:]' '[:lower:]')
  cat << EOF > "$out/$prefix-${name%.md}.html"
$(pr site-head)
<body>
$(pr site-header | sed 's/^/\t/')
  <main>
    <article>
$(render "$file" | sed 's/^/\t\t\t/')
    </article>
  </main>
$(pr site-footer | sed 's/^/\t/')
EOF
  cat << EOF > "$out/content/$prefix-${name%.md}.html"
$(render "$file")
EOF
}

build_dir() {
  local prefix="$1" src="$2"
  for file in "$src"/*.md; do
    if [[ -f "$file" && "$file" != "$src/list.md" ]]; then
      build_file "$file" "$src" "$prefix"
    fi
  done
}